"""add is_deleted to patient

Revision ID: 4aaae10da0a7
Revises: 
Create Date: 2026-03-07 03:09:32.431059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aaae10da0a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication',
    sa.Column('med_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('med_id')
    )
    op.create_table('staff',
    sa.Column('staff_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('staff_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('inventory',
    sa.Column('inv_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('med_id', sa.BigInteger(), nullable=False),
    sa.Column('in_day', sa.Date(), nullable=False),
    sa.Column('exp_day', sa.Date(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['med_id'], ['medication.med_id'], ),
    sa.PrimaryKeyConstraint('inv_id')
    )
    op.create_table('patient',
    sa.Column('p_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('citizen_id', sa.String(length=13), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('age', sa.BigInteger(), nullable=False),
    sa.Column('gender', sa.String(length=100), nullable=False),
    sa.Column('doctor_id', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('p_id'),
    sa.UniqueConstraint('citizen_id')
    )
    op.create_table('stock_log',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('med_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('price_per_unit', sa.BigInteger(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['med_id'], ['medication.med_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('treatment',
    sa.Column('t_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('p_id', sa.BigInteger(), nullable=False),
    sa.Column('med_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['med_id'], ['medication.med_id'], ),
    sa.ForeignKeyConstraint(['p_id'], ['patient.p_id'], ),
    sa.PrimaryKeyConstraint('t_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treatment')
    op.drop_table('stock_log')
    op.drop_table('patient')
    op.drop_table('inventory')
    op.drop_table('staff')
    op.drop_table('medication')
    # ### end Alembic commands ###
