"""add exp_date to treatment

Revision ID: 9eae46375413
Revises: 4aaae10da0a7
Create Date: 2026-03-07 13:46:19.602629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eae46375413'
down_revision: Union[str, Sequence[str], None] = '4aaae10da0a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment', sa.Column('exp_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatment', 'exp_date')
    # ### end Alembic commands ###
